
City.create(ville: "ANTSIRANANA")
City.create(ville: "MAHAJANGA")
City.create(ville: "TOAMASINA")
City.create(ville: "ANTANANARIVO")
City.create(ville: "FIANARANTSOA")
City.create(ville: "TOLIARA")


Genre.create(list: "sport")
Genre.create(list: "spectacle")
Genre.create(list: "cabaret")
Genre.create(list: "soiree")
Genre.create(list: "balle")
Genre.create(list: "scolaire")
Genre.create(list: "festival")
Genre.create(list: "foire")
Genre.create(list: "salon")
Genre.create(list: "teatre")
Genre.create(list: "evangelique")